package vista;

import modelo.Pedido;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;

public class VentanaListaPedidos extends JFrame {
    private JPanel panel1;
    private JTable table1;
    private DefaultTableModel modeloTabla;

    public VentanaListaPedidos(ArrayList<Pedido> lista) {
        setContentPane(panel1);
        setTitle("Lista de Pedidos");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Configurar JTable (Paso 3)
        String[] columnas = {"ID", "Tipo", "Dirección", "Estado"};
        modeloTabla = new DefaultTableModel(columnas, 0);
        table1.setModel(modeloTabla);

        // Timer para refrescar la tabla cada segundo y ver el avance de los hilos
        Timer timer = new Timer(1000, e -> refrescarTabla(lista));
        timer.start();

        refrescarTabla(lista);
        pack();
    }

    private void refrescarTabla(ArrayList<Pedido> lista) {
        modeloTabla.setRowCount(0);
        for (Pedido p : lista) {
            Object[] fila = {
                    p.getId(),
                    p.getClass().getSimpleName().replace("Pedido", ""),
                    p.getDireccionEntrega(),
                    p.getEstado()
            };
            modeloTabla.addRow(fila);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        table1 = new JTable();
        panel2.add(table1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel2.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }
}