package vista;

import modelo.*;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class VentanaPrincipal extends JFrame {
    private JPanel panel1;
    private JButton btnRegistrar;
    private JButton btnIniciarEntregas;
    private JTextArea areaConsola;
    private JButton btnlistarPedidos;

    private ArrayList<Pedido> listaPedidos;

    public VentanaPrincipal() {
        this.listaPedidos = new ArrayList<>();

        // Vincular el diseño
        setContentPane(panel1);
        setTitle("SpeedFast - Gestión de Entregas");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(600, 450);

        // --- EVENTOS ---

        btnRegistrar.addActionListener(e -> {
            VentanaRegistroPedido vRegistro = new VentanaRegistroPedido(listaPedidos);
            vRegistro.setVisible(true);
        });

        btnIniciarEntregas.addActionListener(e -> {
            if (listaPedidos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay pedidos pendientes.");
                return;
            }
            iniciarProcesoDeReparto();
        });

        btnlistarPedidos.addActionListener(e -> {
            areaConsola.append("Listando pedidos desde la memoria...\n");
            for (Pedido p : listaPedidos) {
                areaConsola.append("- " + p.getDireccionEntrega() + " (" + p.getEstado() + ")\n");
            }
        });

        setLocationRelativeTo(null);
    }

    private void iniciarProcesoDeReparto() {
        ZonaDeCarga zona = new ZonaDeCarga();
        for (Pedido p : listaPedidos) {
            zona.agregarPedido(p);
        }
        listaPedidos.clear();

        areaConsola.append(">>> Iniciando hilos de reparto...\n");

        Thread hilo1 = new Thread(new Repartidor(1, "Carlos", zona));
        Thread hilo2 = new Thread(new Repartidor(2, "Elena", zona));

        hilo1.start();
        hilo2.start();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        btnRegistrar = new JButton();
        btnRegistrar.setText("Registrar pedido");
        panel1.add(btnRegistrar, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnlistarPedidos = new JButton();
        btnlistarPedidos.setText("Listar pedidos");
        panel1.add(btnlistarPedidos, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnIniciarEntregas = new JButton();
        btnIniciarEntregas.setText("Iniciar entrega");
        panel1.add(btnIniciarEntregas, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}